# Generated by Django 4.2.3 on 2023-07-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=500, verbose_name='Direccion')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('cuil', models.IntegerField(unique=True, verbose_name='CUIL')),
                ('responsable', models.CharField(max_length=50, verbose_name='responsable')),
                ('factura', models.CharField(max_length=5, verbose_name='Factura')),
                ('rubro', models.CharField(max_length=50, verbose_name='Rubro')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
        ),
    ]
