# Generated by Django 4.2.3 on 2023-07-08 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='factura',
            new_name='facturaT',
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(verbose_name='DD')),
                ('mes', models.IntegerField(verbose_name='MM')),
                ('anio', models.IntegerField(verbose_name='AAAA')),
                ('facturaN', models.IntegerField(verbose_name='N° Factura')),
                ('producto', models.CharField(max_length=50, verbose_name='Producto')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.FloatField(default=0, verbose_name='Precio Unitario')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('facturaT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturat', to='proveedores.proveedor', verbose_name='Tipo Factura')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedor', to='proveedores.proveedor', verbose_name='Proveedor')),
            ],
        ),
    ]
