# Generated by Django 4.2.3 on 2023-07-08 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_ususario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ususario',
            new_name='Usuario',
        ),
    ]
